### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by MaxWindt** [MaxWindt/live_audio_broadcaster#22]
Here are the code snippets for the three improvements:

### 2. Replace "X" with a proper Material Design icon

```html
<button class="mdl-button mdl-button--icon close-dialog">
  <i class="material-icons">close</i>
</button>
```

### 4. Prevent saving empty recordings in auto-stop

```javascript
var handleStop = function () {
  debug("handleStop called");
  try {
    var blob = new Blob(recordedChunks, {
      type: "audio/webm",
    });
    debug("Blob created, size:", blob.size);
    
    // Don't save the recording if it was auto-stopped due to silence
    if (silenceStart && Date.now() - silenceStart >= stopAfterMinutesSilence * 60 * 1000) {
      debug("Skipping save for auto-stopped silence recording");
      recordedChunks = [];
      return;
    }
    
    sendBlob(blob);
  } catch (error) {
    debug("Error creating blob:", error);
  }
};
```

### 8. Simple recording button with blinking effect

```html
<button id="record" class="mdl-button mdl-js-button mdl-button--fab">
  <i class="material-icons">mic</i>
</button>
```

```css
@keyframes blink-recording {
  0% { background-color: #f44336; }
  50% { background-color: #ef9a9a; }
  100% { background-color: #f44336; }
}

.recording-active {
  background-color: #f44336 !important;
  color: white !important;
  animation: blink-recording 2s infinite;
}
```

```javascript
var toggleRecording = function () {
  debug("toggleRecording called, current recording state:", recording);
  if (recording) {
    stopRecording();
  } else {
    startRecording();
  }
};

var startRecording = function () {
  debug("startRecording called");
  if (!mediaRecorder) {
    debug("Error: mediaRecorder not initialized");
    return;
  }

  try {
    recordedChunks = [];
    mediaRecorder.start();
    recording = true;
    var recordButton = document.getElementById("record");
    recordButton.classList.add("recording-active");
    recordButton.innerHTML = '<i class="material-icons">stop</i>';
    debug("Recording started successfully");
  } catch (error) {
    debug("Error starting recording:", error);
  }
};

var stopRecording = function () {
  debug("stopRecording called");
  if (!mediaRecorder) {
    debug("Error: mediaRecorder not initialized");
    return;
  }

  try {
    mediaRecorder.stop();
    recording = false;
    var recordButton = document.getElementById("record");
    recordButton.classList.remove("recording-active");
    recordButton.innerHTML = '<i class="material-icons">mic</i>';
    debug("Recording stopped successfully");
  } catch (error) {
    debug("Error stopping recording:", error);
  }
};
```
